const MODELS_DEV_URL = "https://models.dev/api.json";
const OPENROUTER_URL = "https://openrouter.ai/api/v1/models";
const VERCEL_AI_GATEWAY_URL = "https://ai-gateway.vercel.sh/v1/models";

const MODELS_DEV_PROVIDERS = Object.freeze([
  {
    source: "openai",
    target: "openai",
    openAiResponsesOnly: true,
    developerRole: true,
  },
  { source: "anthropic", target: "anthropic" },
  { source: "groq", target: "groq" },
  { source: "cerebras", target: "cerebras" },
  { source: "xai", target: "xai" },
  { source: "zai-coding-plan", target: "zai" },
  { source: "huggingface", target: "huggingface" },
  { source: "fireworks-ai", target: "fireworks" },
  { source: "opencode", target: "opencode", openAiCompatibleOnly: true },
  { source: "opencode-go", target: "opencode-go", openAiCompatibleOnly: true },
  { source: "minimax", target: "minimax" },
  { source: "minimax-cn", target: "minimax-cn" },
  { source: "moonshotai", target: "moonshotai" },
  { source: "moonshotai-cn", target: "moonshotai-cn" },
]);

export const MODEL_SOURCE_URLS = Object.freeze({
  modelsDev: MODELS_DEV_URL,
  openRouter: OPENROUTER_URL,
  vercelAiGateway: VERCEL_AI_GATEWAY_URL,
});

export async function generateModels(input = {}) {
  const fetchImpl = input.fetch ?? globalThis.fetch;
  if (typeof fetchImpl !== "function") throw new Error("Model generator requires fetch");
  const [modelsDev, openRouter, vercel] = await Promise.all([
    fetchJson(fetchImpl, MODELS_DEV_URL, "models.dev"),
    fetchJson(fetchImpl, OPENROUTER_URL, "OpenRouter"),
    fetchJson(fetchImpl, VERCEL_AI_GATEWAY_URL, "Vercel AI Gateway"),
  ]);

  const grouped = new Map();
  normalizeModelsDev(modelsDev, grouped);
  addModels(grouped, "deepseek", officialDeepSeekModels());
  addModels(grouped, "openrouter", normalizeOpenRouter(openRouter));
  addModels(grouped, "vercel-ai-gateway", normalizeVercel(vercel));
  requireDefaultModel(grouped, "deepseek", "deepseek-flash");

  return Object.freeze(Object.fromEntries(
    [...grouped.entries()]
      .sort(([left], [right]) => left.localeCompare(right))
      .map(([provider, models]) => [
        provider,
        Object.freeze([...models.values()].sort((left, right) =>
          left.id.localeCompare(right.id)
        )),
      ]),
  ));
}

export function renderGeneratedModels(models) {
  const serialized = JSON.stringify(models, null, 2);
  return `// This file is generated by scripts/models/generate-models.mjs.
// Do not edit it manually. Run \`npm run models:generate\` to refresh it.
// Sources: models.dev, OpenRouter, Vercel AI Gateway, and the reviewed DeepSeek API contract.

import type { ModelSpec } from "./types.js";

export const GENERATED_MODELS = ${serialized} as const satisfies
  Readonly<Record<string, readonly ModelSpec[]>>;
`;
}

async function fetchJson(fetchImpl, url, label) {
  let response;
  try {
    response = await fetchImpl(url, {
      headers: { accept: "application/json" },
      signal: AbortSignal.timeout(30_000),
    });
  } catch (error) {
    throw new Error(`${label} model source could not be fetched`, { cause: error });
  }
  if (response === null || typeof response !== "object" || response.ok !== true) {
    const status = typeof response?.status === "number" ? ` (${response.status})` : "";
    throw new Error(`${label} model source returned an unsuccessful response${status}`);
  }
  try {
    return await response.json();
  } catch (error) {
    throw new Error(`${label} model source did not return valid JSON`, { cause: error });
  }
}

/**
 * DeepSeek's official contract takes precedence over lagging third-party indexes.
 * The current API has time-dependent peak/off-peak prices. Runtime Pricing owns
 * that schedule; omitting a static ModelPrice avoids reporting one period as universal.
 * Reviewed against https://api-docs.deepseek.com/quick_start/pricing/ and
 * https://api-docs.deepseek.com/guides/vision/ on 2026-09-16.
 */
function officialDeepSeekModels() {
  const current = {
    contextWindowTokens: 1_000_000,
    maxOutputTokens: 393_216,
    image: true,
    reasoning: true,
    reasoningControl: { format: "deepseek-chat", efforts: ["none", "low", "high", "max"], defaultEffort: "high" },
  };
  return [
    baseModel({ id: "deepseek-flash", name: "DeepSeek V4.1 Flash", status: "active", ...current }),
    baseModel({ id: "deepseek-v4-flash", name: "DeepSeek V4 Flash (legacy alias)", status: "deprecated", ...current }),
    baseModel({ id: "deepseek-v4-flash-vision-exp", name: "DeepSeek V4 Flash Vision Exp (legacy alias)", status: "deprecated", ...current }),
    baseModel({ id: "deepseek-v4-pro", name: "DeepSeek V4 Pro", status: "active",
      contextWindowTokens: 1_000_000, maxOutputTokens: 393_216, image: false, reasoning: true,
      reasoningControl: current.reasoningControl }),
  ];
}

function normalizeModelsDev(value, grouped) {
  const root = record(value, "models.dev response");
  for (const descriptor of MODELS_DEV_PROVIDERS) {
    const provider = record(
      root[descriptor.source],
      `models.dev Provider ${descriptor.source}`,
    );
    const sourceModels = record(
      provider.models,
      `models.dev Provider ${descriptor.source}.models`,
    );
    const models = [];
    for (const [modelId, raw] of Object.entries(sourceModels)) {
      const model = record(raw, `models.dev model ${descriptor.source}/${modelId}`);
      if (model.tool_call !== true || model.status === "deprecated") continue;
      if (
        descriptor.openAiCompatibleOnly === true &&
        !isOpenAiCompatibleModel(model)
      ) continue;
      if (
        descriptor.openAiResponsesOnly === true &&
        !isOpenAiResponsesModel(model)
      ) continue;
      models.push(normalizeModelsDevModel(modelId, model, descriptor));
    }
    addModels(grouped, descriptor.target, models);
  }
}

function isOpenAiCompatibleModel(model) {
  const npm = isRecord(model.provider) ? model.provider.npm : undefined;
  return npm === undefined || npm === null ||
    npm === "@ai-sdk/openai-compatible" || npm === "@ai-sdk/alibaba";
}

function isOpenAiResponsesModel(model) {
  const output = stringArray(recordOrEmpty(model.modalities).output);
  return output.includes("text") && !output.includes("audio");
}

function normalizeModelsDevModel(modelId, model, descriptor) {
  const normalized = baseModel({
    id: modelId,
    name: stringOrUndefined(model.name),
    status: model.status === "deprecated" ? "deprecated" : "active",
    contextWindowTokens: positiveIntegerOrUndefined(recordOrEmpty(model.limit).context),
    maxOutputTokens: positiveIntegerOrUndefined(recordOrEmpty(model.limit).output),
    image: stringArray(recordOrEmpty(model.modalities).input).includes("image"),
    reasoning: model.reasoning === true,
    price: modelsDevPrice(model),
    developerRole: descriptor.developerRole === true,
  });
  if (model.temperature === false) {
    normalized.request = { supportsTemperature: false };
  }
  return normalized;
}

function modelsDevPrice(model) {
  const cost = recordOrEmpty(model.cost);
  if (!nonNegativeNumber(cost.input) || !nonNegativeNumber(cost.output)) {
    return undefined;
  }
  const version = stringOrUndefined(model.last_updated) ??
    stringOrUndefined(model.release_date) ?? "current";
  return price({
    version: `models.dev:${version}`,
    input: cost.input,
    output: cost.output,
    cacheRead: nonNegativeNumber(cost.cache_read) ? cost.cache_read : undefined,
    cacheWrite: nonNegativeNumber(cost.cache_write) ? cost.cache_write : undefined,
  });
}

function normalizeOpenRouter(value) {
  const data = array(record(value, "OpenRouter response").data, "OpenRouter data");
  const models = [];
  for (const raw of data) {
    const model = record(raw, "OpenRouter model");
    const parameters = stringArray(model.supported_parameters);
    if (!parameters.includes("tools")) continue;
    const id = requiredString(model.id, "OpenRouter model.id");
    // Moving aliases can change limits and prices between two consecutive
    // requests. Generate concrete catalog entries only.
    if (isDynamicOpenRouterAlias(id)) continue;
    const architecture = recordOrEmpty(model.architecture);
    const topProvider = recordOrEmpty(model.top_provider);
    const pricing = recordOrEmpty(model.pricing);
    const hasTieredPricing = Array.isArray(pricing.overrides) && pricing.overrides.length > 0;
    const normalized = baseModel({
      id,
      name: stringOrUndefined(model.name),
      status: "active",
      contextWindowTokens: positiveIntegerOrUndefined(model.context_length),
      maxOutputTokens: positiveIntegerOrUndefined(topProvider.max_completion_tokens),
      image: stringArray(architecture.input_modalities).includes("image") ||
        stringOrUndefined(architecture.modality)?.includes("image") === true,
      reasoning: parameters.includes("reasoning") || parameters.includes("include_reasoning"),
      price: hasTieredPricing ? undefined : tokenPrice("openrouter:live", pricing),
    });
    normalized.request = {
      supportsTemperature: parameters.includes("temperature"),
      maxTokensField: parameters.includes("max_completion_tokens")
        ? "max_completion_tokens"
        : "max_tokens",
      ...(normalized.reasoning
        ? { extraBody: { reasoning: { effort: "high" } } }
        : {}),
    };
    models.push(normalized);
  }
  return models;
}

function normalizeVercel(value) {
  const data = array(record(value, "Vercel AI Gateway response").data, "Vercel data");
  const models = [];
  for (const raw of data) {
    const model = record(raw, "Vercel AI Gateway model");
    const tags = stringArray(model.tags);
    if (!tags.includes("tool-use")) continue;
    const modalities = recordOrEmpty(model.modalities);
    models.push(baseModel({
      id: requiredString(model.id, "Vercel AI Gateway model.id"),
      name: stringOrUndefined(model.name),
      status: "active",
      contextWindowTokens: positiveIntegerOrUndefined(model.context_window),
      maxOutputTokens: positiveIntegerOrUndefined(model.max_tokens),
      image: stringArray(modalities.input).includes("image") || tags.includes("vision"),
      reasoning: tags.includes("reasoning"),
      price: tokenPrice("vercel-ai-gateway:live", recordOrEmpty(model.pricing)),
      request: model.temperature === false ? { supportsTemperature: false } : undefined,
    }));
  }
  return models;
}

function tokenPrice(version, raw) {
  const input = perTokenToPerMillion(raw.input ?? raw.prompt);
  const output = perTokenToPerMillion(raw.output ?? raw.completion);
  if (input === undefined || output === undefined) return undefined;
  return price({
    version,
    input,
    output,
    cacheRead: perTokenToPerMillion(raw.input_cache_read),
    cacheWrite: perTokenToPerMillion(raw.input_cache_write),
  });
}

function price({ version, input, output, cacheRead, cacheWrite }) {
  return {
    version,
    currency: "USD",
    inputPerMillionTokens: input,
    ...(cacheRead === undefined ? {} : { cachedInputPerMillionTokens: cacheRead }),
    ...(cacheWrite === undefined
      ? {}
      : { cacheWriteInputPerMillionTokens: cacheWrite }),
    outputPerMillionTokens: output,
  };
}

function perTokenToPerMillion(value) {
  const parsed = typeof value === "number" ? value :
    typeof value === "string" && value.trim().length > 0 ? Number(value) : NaN;
  return Number.isFinite(parsed) && parsed >= 0
    ? Number((parsed * 1_000_000).toPrecision(12))
    : undefined;
}

function isDynamicOpenRouterAlias(id) {
  return id === "auto" || id.endsWith("/auto") || id.startsWith("~") ||
    /(?:^|[-/])latest$/u.test(id);
}

function baseModel(input) {
  const model = {
    id: requiredString(input.id, "model id"),
    ...(input.name === undefined ? {} : { name: input.name }),
    status: input.status,
    ...(input.contextWindowTokens === undefined
      ? {}
      : { contextWindowTokens: input.contextWindowTokens }),
    ...(input.maxOutputTokens === undefined
      ? {}
      : { maxOutputTokens: input.maxOutputTokens }),
    input: { text: true, image: input.image },
    reasoning: input.reasoning,
    ...(input.reasoningControl === undefined ? {} : { reasoningControl: input.reasoningControl }),
    toolCalling: true,
    developerRole: input.developerRole === true,
    ...(input.price === undefined ? {} : { price: input.price }),
  };
  if (input.request !== undefined) model.request = input.request;
  return model;
}

function addModels(grouped, provider, models) {
  if (!Array.isArray(models) || models.length === 0) {
    throw new Error(`Model source produced no supported models for Provider "${provider}"`);
  }
  const current = grouped.get(provider) ?? new Map();
  for (const model of models) {
    if (current.has(model.id)) continue;
    current.set(model.id, model);
  }
  grouped.set(provider, current);
}

function requireDefaultModel(grouped, provider, modelId) {
  if (grouped.get(provider)?.has(modelId) !== true) {
    throw new Error(`Required default model "${provider}/${modelId}" is missing`);
  }
}

function record(value, label) {
  if (!isRecord(value)) throw new Error(`${label} must be an object`);
  return value;
}

function recordOrEmpty(value) {
  return isRecord(value) ? value : {};
}

function isRecord(value) {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

function array(value, label) {
  if (!Array.isArray(value)) throw new Error(`${label} must be an array`);
  return value;
}

function stringArray(value) {
  return Array.isArray(value) ? value.filter((item) => typeof item === "string") : [];
}

function requiredString(value, label) {
  if (typeof value !== "string" || value.length === 0 || value !== value.trim()) {
    throw new Error(`${label} must be a non-empty trimmed string`);
  }
  return value;
}

function stringOrUndefined(value) {
  return typeof value === "string" && value.length > 0 && value === value.trim()
    ? value
    : undefined;
}

function positiveIntegerOrUndefined(value) {
  return Number.isSafeInteger(value) && value > 0 ? value : undefined;
}

function nonNegativeNumber(value) {
  return typeof value === "number" && Number.isFinite(value) && value >= 0;
}
